# A simple script to demonstrate MIE decoding.

import sys
# The sys.path.insert adds the parent directory (the root of the repo)
# to the Python path, allowing us to import from the 'src' folder.
sys.path.insert(0, '../') 

from src.decoder import decode_mie

def main():
    """Decodes a sample MIE message."""
    
    # A pre-encoded MIE message for the text "Hello, MIE!"
    # This was generated by the encode_message.py script.
    encoded_message = "(1*1) 0 (1*1) 0 0 (1*1) (1*1) 0 (1*1) 0 0 (1*1) 0 (1*1) (1*1) (1*1) (1*1) (1*1) 0 (1*1) 0 (1*1) (1*1) (1*1) 0 0 0 (1*1) 0 (1*1) (1*1) 0 0 (1*1) (1*1) (1*1) 0 (1*1) (1*1) (1*1) 0 0 (1*1) (1*1) 0 0 0 (1*1) 0 (1*1) (1*1) 0 (1*1) (1*1) 0 0 (1*1) 0 (1*1) 0 (1*1) (1*1) (1*1) 0 (1*1) 0 (1*1) 0 0 0 (1*1) 0 0 (1*1) (1*1) 0 (1*1) 0 0 (1*1) 0 (1*1) (1*1) 0 0 (1*1) (1*1) 0 0 0 0 (1*1) 0 (1*1) 0 (1*1) (1*1) 0 (1*1) (1*1) 0 (1*1) 0 (1*1) 0 0 (1*1) (1*1) 0 (1*1) 0 0 0 (1*1) 0 (1*1) 0 0 (1*1) 0 0 (1*1)"
    
    # Call the decoder function.
    decoded_message = decode_mie(encoded_message)
    
    print(f"MIE Encoded Message: {encoded_message}")
    print(f"Decoded Text: {decoded_message}")

if __name__ == "__main__":
    main()
